---
# Kubernetes initialization parameters
kubeadm_init_upload_certs: true

# User-specific configuration
kube_config_user: "{{ ansible_user | default('ubuntu') }}"
kube_user_home: "/home/{{ kube_config_user }}"
